[package]
name = "rust-repo-template"
version = "0.1.0"
edition = "2021"
authors = ["milosgajdos <milosthegajdos@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
